
export function exportToHtml(
  content: string, 
  domain: string, 
  testType: string,
  customRequirements?: Array<{text: string, rating: number | null}>,
  overallRating?: number | null
): void {
  // Convert markdown content to basic HTML (this is a simple implementation)
  const htmlContent = content
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/gim, '<em>$1</em>')
    .replace(/\n/gim, '<br>');
  
  // Add overall rating if available
  const ratingHtml = overallRating 
    ? `<div class="overall-rating">Overall Rating: ${overallRating} ★</div>` 
    : '';
  
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${testType} Scenarios for ${domain}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #2d63c8;
      border-bottom: 1px solid #eee;
      padding-bottom: 10px;
    }
    h2 {
      color: #3a7bd5;
      margin-top: 30px;
    }
    strong {
      color: #2d63c8;
    }
    .footer {
      margin-top: 50px;
      font-size: 12px;
      color: #888;
      text-align: center;
    }
    .overall-rating {
      color: #f39c12;
      font-weight: bold;
      font-size: 16px;
      text-align: right;
      margin: 20px 0;
    }
  </style>
</head>
<body>
  <h1>${testType} Scenarios for ${domain}</h1>
  
  ${ratingHtml}
  
  <div class="content">
    ${htmlContent}
  </div>
  
  <div class="footer">
    Generated by Gen AI Test-Hub - ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
  `;
  
  // Create a blob and download
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${domain.toLowerCase().replace(/\s+/g, '-')}-${testType.toLowerCase().replace(/\s+/g, '-')}-scenarios.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
